### ISSUE TITLE
Googling for "mongodb node driver insertone" will bring the user to a 404 page.

### ISSUE THREAD

**Issue by t-eckert** [mongodb/docs-node#258]
This issue originates with what Google is indexing for the top result, but probably because something got moved, the first result when I (and maybe most people) search "mongodb node driver insertone" links to [https://docs.mongodb.com/drivers/node/usage-examples/insertOne/](https://docs.mongodb.com/drivers/node/usage-examples/insertOne/).

The actual article the user is looking for is [https://docs.mongodb.com/drivers/node/current/usage-examples/insertOne/](https://docs.mongodb.com/drivers/node/current/usage-examples/insertOne/). The difference here being `current` in the path.

```diff
- https://docs.mongodb.com/drivers/node/usage-examples/insertOne/
+ https://docs.mongodb.com/drivers/node/current/usage-examples/insertOne/
```

It may be worthwhile to add a redirect in your docs code from `https://docs.mongodb.com/drivers/node/*` to `https://docs.mongodb.com/drivers/node/current/*`.

![image](https://user-images.githubusercontent.com/29112081/132967477-d7f9aab1-8f6a-49c1-ab03-c314117adb1a.png)
![image](https://user-images.githubusercontent.com/29112081/132967566-e79a1c43-ca80-4efa-95aa-4d3af7930497.png)

**Comment by terakilobyte** [comment]
Thanks, this is resolved now!
